import type { Metadata } from 'next'
import { League_Spartan } from 'next/font/google'

const leagueSpartan = League_Spartan({
  subsets: ['latin'],
  weight: ['500', '700']
})

export const metadata: Metadata = {
  title: 'Invoice App',
  description:
    'Effortlessly manage invoices and payments with our intuitive Invoice App. Ideal for businesses and freelancers. Generated by create next app.'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={leagueSpartan.className}>
      <body>{children}</body>
    </html>
  )
}
